import numpy as np
import matplotlib.pyplot as plt

# config
max_iterations = 55 # for bisection method
num_points = 100 # for plotting

# from assignment online
def horners_rule(x, coefficients):
    N = len(coefficients)
    y_out = coefficients[-1] * np.ones( np.shape(x) )
    
    for k in np.flip( range(N-1) ):
        y_out = x * y_out + coefficients[k]
    
    return y_out



def my_bisection(f, a, b, tol):
    if f(a) * f(b) >= 0: # same sign
        print("Bisection method fails.")
        return None, None

    while (b - a) / 2.0 > tol: # while the width of the interval is greater than the tolerance
        midpoint = (a + b) / 2.0

        # check midpoint
        if f(midpoint) == 0:
            return ([a,b], midpoint)
        elif f(a) * f(midpoint) < 0: # sign check
            b = midpoint
        else: # must be other side of interval
            a = midpoint

    # return final interval and midpoint as estimated root
    return ([a,b], (a + b) / 2.0)


def main():

    # S1 Question 1
    # Show mathematically that Horner's rule is a valid algorithm for polynomial evaluation.
    # Well, looking at the first few cases, trying to determine a pattern
    # for N = 1:
    # Then, p = a_1 * x + a_0
    # for N  = 2:
    # Then, p = a_2 * x^2 + a_1 * x + a_0
    # and for general N (positive integer):
    # p = a_N * x^N + a_(N-1) * x^(N-1) + ... + a_1 * x + a_0
    # where the N index indicating the degree of the polynomial term
    # ie. a_0 is a constant term, a_1 is the coefficient of x**1, a_2 is the coefficient of x**2, etc.


    # S1 Question 2
    # Create a graph of $f(x)=x^2-4$ using Python's built-in capabilities (i.e., without using Horner's method). On the same axes, create a scatter plot (try using plt.scatter()) of $f(x)$ instead evaluated using the above Horner's method (so, you are free to call horners_rule()). Use 100 points in your scatter plot. In both cases, restrict your input between $x=-3$ and $x=3$.
    x = np.linspace(-3, 3, num_points)
    f = lambda x: x**2 - 4

    coefficients = [ -4, 0, 1 ] # from a_0 to a_{N-1}
    plt.plot(x, f(x), label='f(x)', color='black')
    plt.scatter(x, horners_rule(x, coefficients), color='red', label="Horner's method", s=10)
    plt.show()

    # S1 Question 3
    # Plot $g(x) = (x-2)^9$ using Python's built in capabilities. On the same axes, create a scatter plot of the function evaluated at 1000 points using Horner's method and the coefficients in \eqref{E:expandedHorner}. Restrict your plot to the interval $[1.92, 2.08]$. As an argument in your scatter, use s=1. This sets the size of your scatter to 1. Comment on what you observe
    g = lambda x: (x - 2)**9
    x = np.linspace(1.92, 2.08, num_points)
    y = g(x)
    plt.plot(x, y, label='g(x)', color='black')
    coefficents = [-512, 2304, -4608, 5376, -4032, 2016, -672, 144, -18, 1] # from a_0 to a_{N-1} ASC order
    plt.scatter(x, horners_rule(x, coefficents), color='red', label="Horner's method", s=1)
    plt.show()
    # Observation: The black line (the function itself) is relatively matched up with the scattered points generated by Horner's method. In this interval, this appears to be a relatively well fit line, but anything further would require some actual error checking



    # S2 Question 1
    # Write a function called my_bisection() that estimates a root of $f(x)$ in an interval $[a,b]$. Your function should take an argument tol and terminate when the squeezed interval is within this tolerance. For checking purposes, your function should return both the final interval and its midpoint as an estimated root. Note that this differs from the algorithm we discussed in class in which we only returned the final midpoints as the estimated root. Your function should print out the number of bisection iterates performed. See below for an example of printing out variable values using the Python print command.
    current_iteration = 0

    f = lambda x: x**3 - x - 2
    a = 1
    b = 2
    tol = 1e-3

    while (current_iteration < max_iterations):
        interval, root = my_bisection(f, a, b, tol)

        if interval and root:
            print('After %d iterates, the estimated root is %0.4f' %(current_iteration, root))
            current_iteration += 1
        else:
            print("Bisection method failed")
            break

    print(f"Final interval: {interval}, Estimated root: {root}")


    # S2 Question 2 pt 1
    # Estimate the root of $g(x) = (x-2)^9$ using my_bisection(), using Python's built in commands to define $g(x)$. You are free to set a tolerance to your choose, but you must begin with $a = 1.92$, and $b=2.07$ for the endpoints of your initial interval $[a,b]$. Plot $g(x)$ using built-in methods. Plot the bounding interval as a blue horizontal line on the $x$-axis. Does your interval appear to contain the root?
    current_iteration = 0
    
    g = lambda x: (x - 2)**9
    a = 1.92
    b = 2.07
    tol = 1e-3

    while (current_iteration < max_iterations):
        interval, root = my_bisection(g, a, b, tol)

        if interval and root:
            print('After %d iterates, the estimated root is %0.4f' %(current_iteration, root))
            current_iteration += 1
        else:
            print("Bisection method failed")
            break

    print(f"Final interval: {interval}, Estimated root: {root}")

    x = np.linspace(1.92, 2.08, num_points)
    plt.plot(x, g(x), label='g(x)', color='black')
    #plt.fill_between(x, interval[0], interval[1], color='blue', alpha=0.2, label='Interval')
    plt.axhspan(interval[0], interval[1], color="blue", alpha=0.5)
    plt.show()


    # S2 Question 2 pt 2
    # Estimate the root of $g(x) = (x-2)^9$ using my_bisection(), using Horner's method to define $g(x)$. You are free to set a tolerance to your choose, but you must begin with $a = 1.92$, and $b=2.07$ for the endpoints of your initial interval $[a,b]$. Plot $g(x)$ using built in methods. Plot the bounding interval as a red horizontal line on the $x$-axis. Comment on your result. Is your error within the theoretical bound?
    current_iteration = 0
    
    coefficients = [-512, 2304, -4608, 5376, -4032, 2016, -672, 144, -18, 1] # from a_0 to a_{N-1} ASC order
    g_horner = lambda x: horners_rule(x, coefficients)
    a = 1.92
    b = 2.07
    tol = 1e-3

    while (current_iteration < max_iterations):
        interval, root = my_bisection(g_horner, a, b, tol)

        if interval and root:
            print('After %d iterates, the estimated root is %0.4f' %(current_iteration, root))
            current_iteration += 1
        else:
            print("Bisection method failed")
            break

    print(f"Final interval: {interval}, Estimated root: {root}")

    x = np.linspace(1.92, 2.08, num_points)
    plt.plot(x, g_horner(x), label='g_horner(x)', color='black')
    #plt.fill_between(x, interval[0], interval[1], color='blue', alpha=0.2, label='Interval')
    plt.axhspan(interval[0], interval[1], color="blue", alpha=0.5)
    plt.show()

    # S2 Question 3
    # Use your plots and understanding of the bisection method to explain what went wrong when using Horner's method to evaluate the polynomial.
    

if __name__ == '__main__':
    main()

