[project]
name = "dsai201-intro-data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.56.1",
    "duckdb>=1.4.1",
    "manim>=0.19.0",
    "matplotlib>=3.10.7",
    "paddleocr[all]>=3.2.0",
    "pandas>=2.3.3",
    "sense2vec>=2.0.2",
    "spacy>=3.8.7",
    "speechrecognition[audio]>=3.14.3",
    "vosk>=0.3.45",
]
